language: c

sudo: required
dist: trusty

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Coverage

compiler:
  - clang
  - gcc

notifications:
  email:
    - kdmfoss@gmail.com

install:
 - sudo apt-get install lcov python-pip zlib1g-dev
 - sudo pip install cpp-coveralls
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - make
 - ctest --verbose
 - make install
 - test -f ../target/include/qes.h

after_success:
 - cd ..
 - if [ "$BUILD_TYPE" == "Coverage" ] ; then coveralls -e target -e test  -e util -e zlib -E '.*\.h' -e build/CMakeFiles; fi
