#!/usr/bin/env python3
from sys import argv
import argparse

from Bio import SeqIO

def main():
    # TODO: argparse
    for infile in argv[1:]:
        with open(infile) as fh:
            for seq in SeqIO.parse(fh, 'fasta'):
                print(infile, seq.name, len(seq.seq), sep="\t")
                
if __name__ == "__main__":
    main()
